### PR TITLE
add support for {live: true} option, ala `tail -f`

### PR DESCRIPTION
**Pull request by dominictarr**
this adds support for live streams. this means it is now possible to stream your, say, log file, and the the latest changes. getting the abort state correct is important (though tricky) there is a test too.

I've called the property `live` since that the same as all my level modules, etc

### CODE REVIEW

**Comment by DamonOehlman** [comment]
LGTM :)

How do you feel about incorporating feross' standard validation into the pull-stream modules?  I notice that some of the changes in this PR are around semicolon insertion, but I think your preferred style is omit them.  I'm happy with that, but think it's worth keeping whatever we have consistent.

**Comment by dominictarr** [comment]
I don't like linters, but my policy is if I wrote all the code, no linter, if a group of people have "ownership" then the group can choose. we discussed that here. https://github.com/pull-stream/pull-stream/issues/52

whatever it is, if there is a linter it should run in the prepublish or test scripts

**Comment by DamonOehlman** [comment]
No I've never used one either, as I find that it just adds overhead if you are trying to maintain a large number of modules.  Good to merge then.  Also, I'm happy to move this over to the `pull-stream` org if it makes sense.

**Comment by dominictarr** [comment]
yeah lets move it. this is solid enough. we use it in ssb, and no problems.

**Comment by DamonOehlman** [comment]
Published as `1.0.0` - thought it was probably time it took the plunge :)

**Pull request merged**
